
var soc=soc||{};(function($,soc){'use strict';soc.is_integrated=false;soc.lightboxClass='.modal';soc.initPage=function(){$("a[href^='#']").attr("href",function(i,href){return window.location.href.split('#')[0]+href;});soc.ads(soc.adConfig);if(soc.logged_in){soc.online=setInterval(soc.onlineCheck,300000);soc.ajaxSSO.init();}
soc.gui.init();soc.plugins.init();};soc.ajaxLink=function(link){var $link=$(link),pre_parse=$link.data('pre_parse');if(pre_parse){var split=pre_parse.split('|'),pre_parse_function=soc.dereference(split.shift());if(typeof pre_parse_function==="function"){pre_parse_function.apply($link,split);}}
var href=$link.attr('href'),parts=href.split('/'),next=parts.shift();while(parts.length>0&&next!="x"){next=parts.shift();}
if(parts.length<3){return;}
var mo=parts.shift(),op=parts.shift(),me=parts.shift(),params=$link.data('params');if(/\?/.test(me)){params=$.extend(params,soc.deparam(me.split('?')[1]));me=me.split('?')[0];}
var resolution=$.Deferred();resolution.done(function(){soc.ajax(mo,op,me,params);});var confirm=$link.data('confirm');if(confirm){soc.confirm(confirm,resolution);}else{resolution.resolve();}};soc.dereference=function(ref){var reference=soc,deferenced;$.each(ref.split('.'),function(i,value){if(reference[value]){if(typeof reference[value]==="object"){reference=reference[value];}else{deferenced=reference[value];}}});return deferenced;};var ajaxCommands={js:function(command){$.globalEval(command.code);}};soc.ajaxCommands=function(obj){$.each(obj,function(i,command){if(ajaxCommands[command.command]){ajaxCommands[command.command](command);delete obj[i];}});soc.ajOp(obj);};soc.lightbox=function(id,title,body,footer,size,force){var lightbox=$('#'+id),isNew=true;force=force||false;body=$.trim(body);if(lightbox.length===1){isNew=false;if(size){$('.modal-dialog',lightbox).removeClass('modal-sm modal-lg');}}else{lightbox=$('#s-lightbox').clone(false).attr('id',id);if(!title){$('.modal-header',lightbox).remove();}
$('body').append(lightbox);}
if(size==='lg'||size==='sm'){$('.modal-dialog',lightbox).addClass('modal-'+size);}
if(title){$('.modal-header .h4',lightbox).html(title);}
if(body){if(footer===undefined){$('.modal-footer',lightbox).remove();}
var _body=$(body),mBody=$('.modal-body',lightbox);if(body.substr(0,1)=='<'&&(_body.is('.modal-body')||_body.has('.modal-body').length>0)){mBody.replaceWith(body);}else{mBody.html(body);}}
if(footer){$('.modal-footer',lightbox).html(footer);}
if(force){$('.modal-header [data-dismiss]',lightbox).remove();}
if(isNew){lightbox.on('hide.bs.modal',function(){lightbox.on('hidden.bs.modal',function(){lightbox.remove();});});}
lightbox._deferred=$.Deferred();lightbox.modal({backdrop:(force?'static':true)}).on('show.bs.modal',lightbox._deferred.resolve).modal('show');return lightbox;};soc.ajax=function(mo,op,me,params,callback){var cb=callback||soc.ajaxCommands,url=soc.ajaxurl(mo,op,me);params=params||{};if(!url){return;}
if($.isEmptyObject(params)){params=[""];}
var deferred=$.post(url,{params:params},cb,'json');deferred.fail(function(jqXHR,textStatus,errorThrown){if(console){console.error('soc.ajax error: '+textStatus+':'+errorThrown);}});return deferred;};soc.deparam=function(params){var digitTest=/^\d+$/,keyBreaker=/([^\[\]]+)|(\[\])/g,plus=/\+/g,paramTest=/([^?#]*)(#.*)?$/;if(!params||!paramTest.test(params)){return{};}
var data={},pairs=params.split('&'),current,lastPart;for(var i=0;i<pairs.length;i++){current=data;var pair=pairs[i].split('=');if(pair.length!=2){pair=[pair[0],pair.slice(1).join("=")];}
var key=decodeURIComponent(pair[0].replace(plus," ")),value=decodeURIComponent(pair[1].replace(plus," ")),parts=key.match(keyBreaker);for(var j=0;j<parts.length-1;j++){var part=parts[j];if(!current[part]){current[part]=digitTest.test(parts[j+1])||parts[j+1]=="[]"?[]:{};}
current=current[part];}
lastPart=parts[parts.length-1];if(lastPart=="[]"){current.push(value);}else{current[lastPart]=value;}}
return data;};soc.confirm=function(confirmation,deferred,config){var defaults={id:'s-confirm',title:'',footer:''};config=$.extend({},defaults,config);var backdrop=$('.modal-backdrop'),lbox=$('.modal:visible');var lightbox=soc.lightbox(config.id,config.title,'<div class="h4">'+confirmation+'</div>',config.footer,null,true);if(!config.title){$('.modal-header',lightbox).remove();}
lightbox.on('click','button[data-confirm]',function(){var actedUpon=$(this);if(actedUpon.data('confirm')){deferred.resolve(actedUpon);}else{deferred.reject(actedUpon);}
lightbox.modal('hide');}).one('hidden.bs.modal',soc.stackedModalsReset);lightbox._deferred.done(function(){var z=parseInt(lbox.css('z-index'),10);if(!isNaN(z)){lightbox.css('z-index',z+2);$('.modal-backdrop').not(backdrop).css('z-index',z+1);}});};soc.stackedModalsReset=function(){if($('.modal:visible').length){$('body').addClass('modal-open');}};soc.gui.init();soc.gui=$.extend({},soc.gui,{gui2015:true,init:function(){var init=function(){$(document).on('click','.s-ajax',function(e){e.stopPropagation();e.preventDefault();soc.ajaxLink(this);}).on('click','.s-gui',function(e){e.preventDefault();var trigger=$(this).data('gui');if(soc.gui.click[trigger]){soc.gui.click[trigger].call(this);}}).tooltip({trigger:"hover",selector:"[data-toggle=tooltip]",container:"body",html:true});this.search();this.more();this.toolbox();this.facade();this.nav();};setTimeout(function(){init.call(soc.gui);},15);},click:{logout:function(){soc.lightbox('s-logout');},help:function(){window.open($(this).attr('href'),'_blank','resizable=yes,location=yes,toolbar=no,menubar=yes,directories=no,'+'status=yes,scrollbars=yes,height=600,width=800',false);},addpage:function(){soc.ajax("us","glob","addLink",{clean:{title:document.title,loc:window.location.href}});}},search:function(){$('.s-gui[data-search="expand"]').one('click mouseover',function(){var search=$('.s-header-search');search.collapse('show');$(this).click(function(){search.collapse('toggle');});});var q_text='input[name="qtext"]',q_type='input[name="qsearch"]';$('.s-gui-search').on('click','a',function(e){e.preventDefault();var $this=$(this),search=$this.closest('.s-gui-search'),text=search.find(q_text),type=search.find(q_type);type.val($this.data('search'));text.attr('placeholder',$.trim($this.text())).focus();}).submit(function(e){var val=$(this).find(q_text).val();if($.trim(val).length===0){e.preventDefault();}});},more:function(){var more=$('.s-more'),moreClose=function(){more.removeClass('s-more-expand-3');$('.s-more-links-admin').one($.support.transition.end,function(){more.removeClass('s-more-expand');}).emulateTransitionEnd(350);setTimeout(function(){more.removeClass('s-more-expand-2');if($('.s-more-links-admin').length===0){more.removeClass('s-more-expand');}},150);};more.on('click mouseover','.s-more-button, .s-more-button-admin',function(e){if($(this).is('.s-more-button-mobile')){if(e.type=="click"){$('.s-more-wrap').collapse('toggle');}}else if(more.is('.s-more-expand')){if(e.type=='mouseover'){return;}
if(!more.is('.s-more-expand-3')){return;}
moreClose();}else{$(window).one('resize',function(){moreClose();});$('.s-more-wrap').css('height','auto');$('.s-more-links').one($.support.transition.end,function(){setTimeout(function(){more.addClass('s-more-expand-3');},500);more.addClass('s-more-expand-2');}).emulateTransitionEnd(350);more.addClass('s-more-expand');}});},toolbox:function(){var toolbox=$('.s-toolbox');if(toolbox.length===0){return;}
var fadeIn=function(){setTimeout(function(){toolbox.addClass('in');},50);},body_width=$('body').width(),desktop=$('.s-toolbox-indicator').css('display')!='none';if(desktop){var primary_actions=$('.s-toolbox-actions',toolbox),share=$('.s-toolbox-share ',toolbox);primary_actions.toggleClass('btn-group-vertical');share.appendTo(primary_actions).children(':first').unwrap();$('[data-placement="top"]',primary_actions).attr('data-placement','right');toolbox.addClass('s-toolbox-left');$('[data-toggle="tooltip"]',primary_actions).attr('title',function(i,title){return'<span class=\"s-toolbox-tooltip\">'+title+'</span>'});$('.s-toolbox-actions-secondary > .dropdown-menu').removeClass('dropdown-menu-right');if(body_width<=1024){$('.btn-group',toolbox).addClass('btn-group-sm');}}else{fadeIn();return}
var width=toolbox.width(),alignToolbox=function(){var left=((body_width-$('.s-page').innerWidth())/2)-width;if(left<=0){left=0;}
toolbox.css('left',left);};alignToolbox();toolbox.affix({offset:{top:function(){return(this.top=toolbox.offset().top);}}});fadeIn();setTimeout(function(){$(window).one('resize',alignToolbox);},1500);},facade:function(){if(soc.is_integrated){return;}
var selector='.uidtooltip[data-facade]',getFacadeData=function(link,uid,callback){$.get('x/us/glob/facade/uid/'+uid,function(facade){link.data('content',facade);callback(facade);});},preloadFacades=function(){var facade_preload_quantity=10;var facade_preload_limit=50;var link_list=$(selector);if(link_list.length<=facade_preload_limit){$.each(link_list.slice(0,facade_preload_quantity),function(){var link=$(this),uid=link.attr('href').split("=")[1];getFacadeData(link,uid,function(data){var images=$('img[src]',data);images.each(function(i,v){var image=new Image();image.src=v.src;});});});}};preloadFacades();$(document).on('mouseover',selector,function(){var $this=$(this),data=$this.data(),uid=parseInt(data.facade.split('/').pop(),10),content=data.content||false,facade_init='s-gui-facade-init',init=$this.hasClass(facade_init);if(uid===0){return;}
if($this.is('.popover-content .uidtooltip')){return;}
var hide=function(){$this.popover('hide');$('.tooltip').hide();},prepareHide=function(){var hiding=setTimeout(hide,500);$this.data('bs.popover').$tip.one('mouseenter',function(){$this.data('bs.popover').$tip.one('mouseleave',function(){prepareHide();});clearTimeout(hiding);});},showFacade=function(){var popover=$this.data('bs.popover').$tip||$();if(popover.length>0&&popover.is(":visible")){return;}
$(selector).filter('.'+facade_init).not($this).popover('hide');$this.data('bs.popover').options.placement=facadePlacement();$this.popover('show');$this.data('bs.popover').options.placement=facadePlacement();$this.one('mouseleave',function(){var hiding=setTimeout(hide,500);$this.data('bs.popover').$tip.one('mouseenter',function(){clearTimeout(hiding);$(this).one('mouseleave',prepareHide);});});},initFacade=function(){$this.popover({trigger:"manual",placement:facadePlacement,container:"body",html:true,content:function(){return $(this).data('content');}});$this.addClass(facade_init);},facadePlacement=function(){var defaultHeight=300;var facadeHeight=defaultHeight;if($this.data('bs.popover').$tip){facadeHeight=$this.data('bs.popover').$tip[0].getBoundingClientRect().height||defaultHeight;}
if(facadeHeight>0&&$this[0].getBoundingClientRect().top<facadeHeight){return'right';}else{return'top';}},fetchAndShowFacade=function(){getFacadeData($this,uid,showFacade);},doFacade=function(){if(init&&content){showFacade();return;}
initFacade();if(content){showFacade();}else{fetchAndShowFacade();}};var spam=setTimeout(doFacade,100);$this.one('mouseleave',function(){clearTimeout(spam);});});},feedback:{addComment:function(){this.attr('href',function(i,href){var ts=$('.s-gui-feedback-comment:last').data('created');if(!ts){ts=0;}
if(/&ts=/.test(href)){return href.replace(/&ts=[0-9]+/,'&ts='+ts);}else{return href+'&ts='+ts;}});},appendComments:function(comments){$('.s-gui-feedback-comments').append(decodeURIComponent(comments.replace(/\+/g,' ')));soc.scrollTo($('.s-gui-feedback-comment:last').position().top);soc.gui.feedback.setCommentCount();},setCommentCount:function(){var comment_count=$('.s-gui-feedback-comment').length;if(comment_count===1){comment_count="1 Comment";}else{comment_count+=" Comments";}
$('.s-gui-feedback-comment-count-value').html(comment_count);},deleteComment:function(){soc.gui.feedback.setCommentCount();},setLikes:function(likes){if(likes===1){likes="1 Like";}else{likes=likes+" Likes";}
$('.s-gui-feedback-likes-value').html(likes);$('.s-gui-feedback-like').toggleClass('hide');}},nav:function(){if(!$('.navbar-toggle').is(':visible')){$('.navbar-nav .dropdown-toggle').removeAttr('data-toggle');$(document).on('click','.navbar-nav .dropdown-toggle',function(e){e.preventDefault();});}}});soc.tinymce=function(config,baseURL){if(!soc.mce){$(document).on('focusin',function(e){if($(e.target).closest(".mce-window").length&&!tinymce.isIE){e.stopImmediatePropagation();}});}
var socimage=config.socimagekeys||false;soc.mce=config;config.setup=function(editor){tinymce.baseURL=baseURL;if(socimage){var module={comp:parseInt($('#'+socimage.comp).val(),10),compid:parseInt($('#'+socimage.compid).val(),10),compitemid:parseInt($('#'+socimage.compitemid).val(),10)};if(!isNaN(module.comp)&&module.comp!==0){editor.settings.file_browser_callback=function(field_name,url,type,win){if(!tinymce.tinyImage){tinymce.tinyImage=new soc.tinyImage({module:module});}
tinymce.tinyImage.lightbox(field_name);}}}};config.image_advtab=true;$(config.selector).tinymce(config);};soc.addData=function(data_key,selector,key){var val=$(selector).val();if(key){var obj={};obj[key]=val;val=obj;}
this.data(data_key,val);};soc.module={};soc.tinyImage=function(config){this.module=$.extend({},this.module,config.module);};soc.tinyImage.prototype={module:{comp:0,compid:0,compitemid:0},field:'',bounduploader:false,itemClass:'s-socimage-item',ajax:function(method,params,callback){var data=$.extend({},this.module,params);return soc.ajax('Media','TinyMCE',method,data,callback);},lightbox:function(field_name){this.field=field_name;this.prepPage().openLightbox().done($.proxy(this.fixLightbox,this)).done($.proxy(this.bindLightbox,this)).done($.proxy(this.bindUploader,this));},prepPage:function(){this.currentModal=$('.modal-backdrop');return this;},openLightbox:function(){return this.ajax('lightbox',{},undefined);},fixLightbox:function(){var z_index=$('#mce-modal-block').css('z-index')||999999;z_index+=100;this.container=$(soc.lightboxClass+' [data-socimage]');this.iframe=this.container.find('iframe');this.container.closest(soc.lightboxClass).css('z-index',z_index);$('.modal-backdrop').not(this.currentModal).css('z-index',z_index-1);},bindLightbox:function(){this.container.on('click','[data-action="add"]',$.proxy(this.addImage,this)).on('click','.s-socimage-thumbnail > .thumbnail',$.proxy(this.insertImage,this)).closest(soc.lightboxClass).one('hidden.bs.modal',soc.stackedModalsReset);},bindUploader:function(){this.bounduploader=true;window.finishUpload=$.proxy(this.upload,this);this.container.on('resetIFrame',this.resetUpload);},addImage:function(e){var src=this.container.data('src');src+=encodeURIComponent('/'+$('[data-less="soc"]').attr('href'));this.iframe.attr('src',src);$(e.currentTarget).toggleClass('hide');if(this.bounduploader){this.bindUploader();}
$('.'+this.itemClass,this.container).toggleClass('hide');},insertImage:function(e){e.preventDefault();var data=$(e.currentTarget).data();var title=(data.alt!=='')?data.alt:data.title;$('#'+this.field).val(data.src).closest('.mce-container').next().find('.mce-textbox').val(title);this.container.closest(soc.lightboxClass).closeLightBox();},upload:function(filename,fid,info){var alt=$('#s-socimage-description-input').val();this.ajax('upload',{upload:{fid:fid,filename:filename,filealt:alt}},function(data){var cloner=$('.s-socimage-thumbnail-clone'),clone=cloner.clone();clone.removeClass('s-socimage-thumbnail-clone hide');clone.find('img').attr('src',data.thsrc);clone.find('a').data({title:data.title,src:data.src,alt:data.description});cloner.closest('.row').append(clone);setTimeout(function(){clone.find('.thumbnail').trigger('click');},500);});},resetUpload:function(){$('[data-action="add"]',this.container).toggleClass('hide');this.iframe.attr('src','');$('.'+this.itemClass,this.container).toggleClass('hide');}};soc.remoteTabs=function(tabid){$('#'+tabid).on('click','.ui-tabs-nav .ui-tabs-nav-item a',function(event){var link=$(this),loadurl=link.data('load');if(!loadurl){return;}
var label=link.text(),targ='#'+link.attr('href').split('#')[1],loaded=$.trim($(targ).html()).length!==0;if(loaded){return;}
event.preventDefault();var span=$('span',link);span.text('Loading...');$(targ).load(loadurl,function(){link.tab('show');span.text(label);});}).find('.ui-tabs-nav .ui-tabs-nav-item.active a').trigger('click');};})(jQuery,soc);(function($,soc,compat){compat.fillLbCommon=function(refid,refrpc,html,title,w,refid2,refid3,postcb,pc){var id='popclick'+pc,size=compat.lightboxSize(w),force=refid2==='MODAL',oldForm;if($.trim(html).substr(0,1)!='<'){html='<div>'+html+'</div>';}
var $html=$(html);if($html.is('.s-form')){}else if($html.is('form')){oldForm=$html;}else{oldForm=$html.find('form');}
var lightbox=soc.lightbox(id,title,html,undefined,size,force);lightbox._deferred.done(function(){if(oldForm){oldForm=lightbox.find('form');soc.loader.load('js/jquery-form.js');soc.loader.whenLoaded('jquery-form',function(){compat.bindAjaxForm.call(oldForm,postcb,refrpc,refid,refid2,refid3);});if(soc.mce){var tinys=$('.mceEditor',lightbox);if(tinys.length>0){lightbox.on('hide.bs.modal',function(){tinys.each(function(){tinyMCE.execCommand('mceRemoveEditor',true,$(this).attr('id'));});});compat.bindTinyMCEForm.call(oldForm,tinys,soc.mce);}}}
lightbox.one('click','.jqmClose',function(e){e.preventDefault();$(this).closest(soc.lightboxClass).jqmHide();});});};compat.lightboxSize=function(width){var size;if(width==="lg"||width==="sm"){return width;}
width=parseInt(width,10);if(width>600){size="lg";}else if(width<=300){size="sm";}
return size;};compat.popDivLb=function(width,title,content_id,window_id){return soc.lightbox(window_id||"popclick",title,$('#'+content_id).html(),null,compat.lightboxSize(width));};$.fn.closeLightBox=$.fn.jqmHide=function(){return this.modal('hide');};$.fn.jqmShow=function(){return this.modal('show');};$.fn.jqm=function(){return this;};$.fn.jqDrag=$.fn.jqmResize=$.fn.cluetip=$.noop;})(jQuery,soc,window);(function($,module){module.forum={thread:{easy:function(){$('.s-fo-easy-thread button').on('click',function(event){var container=$(event.currentTarget).closest('.s-fo-easy-thread'),input=container.find('[name="easy-thread-message"]'),message=input.val();if(message.length===0){return;}
var d=$.Deferred();d.done(function(e){var params=container.data();params.utf8=1;if(e.data('action')=='post'){params.thread_data={message:message};soc.ajax('Forum','Topic','createThread',params)}else{params.subject=message;params.message=message;soc.redirect('p/fo/ct/'+$.param(params));}});var config={footer:$('.s-fo-easy-thread-buttons').clone().removeClass('hide').html()};soc.confirm('Post message as-is or edit in advanced editor?',d,config);});}}};module.download={showdownload:{init:function(media_json){var media=media_json?JSON.parse(media_json):{},options=null;if(media&&(media.image||media.video||media.audio)){this.listen();if(media.image){this.loadImage(media.image.fid,media.image.src,media.image.title);}else if(media.video){options={'element':{'width':media.video.w,'height':media.video.h,'style':"width:100%;height:100%;"}};this.loadMedia('video',media.video.fid,media.video.src,options);}else if(media.audio){options={'element':{'style':"width:100%;height:100%;"}};this.loadMedia('audio',media.audio.fid,media.audio.src,options);}}},showImageIcon:function(element){var thisElement=$(element),img_data=thisElement.data();var img_src='media/'+img_data['filename'];$('.download-image-preview img').attr('src',img_src);$('.download-preview-title').text(img_data['title']);},loadImage:function(fid,src,title){$('.s-do-download-waiting','.s-do-download').removeClass('hidden');$('<div>').attr({'class':'image-wrapper','data-fid':fid}).append($('<img>').attr({'id':'img_'+fid,'class':"img-responsive center-block hidden",'alt':title})).appendTo('.image-container','.s-do-download');$('#img_'+fid,'.image-container').one('load',function(){$('.s-do-download-waiting','.s-do-download').addClass('hidden');$('.img-responsive','.s-do-download').removeClass('hidden');}).attr({'src':src});},loadMedia:function(mediaType,fid,src,options){var tag='<'+mediaType+'>',id=mediaType+'_player_'+fid,wrapperClass=mediaType+'-wrapper',containerClass='.'+mediaType+'-container',elemAttributes=options&&options.element?options.element:{},playerConfig=options&&options.player?options.player:{"pluginPath":soc.plugins.video.path,"success":function(player,domElement){var autoplay=typeof $(domElement).data('autoplay')!='undefined'?$(domElement).data('autoplay'):false;if(autoplay){player.play();}
$('.media-view','.s-do-download').on('click',function(e){e.preventDefault();try{player.pause();}catch(e){}});}};soc.plugins.video.init({"init":{"autoload":false}});$('<div>').attr({'class':wrapperClass,'data-fid':fid}).append($(tag).attr($.extend({'id':id,'src':src},elemAttributes))).appendTo(containerClass,'.s-do-download');soc.loader.whenLoaded(soc.plugins.video.path+soc.plugins.video.scriptFile,function(){$('#'+id).mediaelementplayer(playerConfig);});},listen:function(){$('.s-do-download-file','.s-do-download').on('click','.media-view',function(e){e.preventDefault();var mediaType=$(this).data('media-type'),fid=$(this).data('fid'),title=decodeURIComponent($(this).data('title')),src=decodeURIComponent($(this).data('src')),options=null;switch(mediaType){case"image":if(!$('#img_'+fid,'.s-do-download').length>0){soc.module.download.showdownload.loadImage(fid,src,title);}
break;case"audio":if(!$('#audio_player_'+fid,'.s-do-download').length>0){options={'element':{'style':'width:100%;height:100%','data-autoplay':true}};soc.module.download.showdownload.loadMedia(mediaType,fid,src,options);}
break;case"video":if(!$('#video_player_'+fid,'.s-do-download').length>0){options={'element':{'width':$(this).data('w'),'height':$(this).data('h'),'style':'width:100%;height:100%','data-autoplay':true}};soc.module.download.showdownload.loadMedia(mediaType,fid,src,options);}
break;default:break;}
$('#'+mediaType+'_title','.s-do-download').text(title);$('.'+mediaType+'-wrapper[data-fid="'+fid+'"]','.s-do-download').removeClass('hidden');$('.'+mediaType+'-wrapper[data-fid!="'+fid+'"]','.s-do-download').addClass('hidden');$('.s-do-download-media-container[data-media-type="'+mediaType+'"]','.s-do-download').removeClass('hidden');$('.s-do-download-media-container[data-media-type!="'+mediaType+'"]','.s-do-download').addClass('hidden');});}}};module.shared={export:{init:function(){$(document).on('click','a.export',function(e){var link=$(this),data=link.data(),check,checkDone=function(){soc.ajax('Shared','Export','check',data,function(response){if(response.file){soc.injectDownload(response.file);resetUI(response.file);}else if(response.files){resetUI('#');link.remove();var list=$('.export-all.hide.list-group'),dl=function(href,label){return'<li class="list-group-item">'
+'<div class="btn-group btn-group-justified">'
+'<a href="'+href+'" class="btn btn-default">'
+'<span class="fa fa-download"></span> '+label
+'</a></div></li>'};$.each(response.files,function(type,url){list.append(dl(url,type));});list.removeClass('hide');}});},notifyUI=function(){soc.toggleProgress(true);var icon=$('.fa',link);link.text(' Export Running...');icon.attr('class','fa fa-spinner fa-spin');link.prepend(icon);check=setInterval(checkDone,10000);},resetUI=function(href){clearInterval(check);soc.toggleProgress(false);var icon=$('.fa-spinner',link);link.attr('href',href);link.text(' Download Export');icon.removeClass('fa-spinner fa-spin').addClass('fa-download');link.prepend(icon);link.removeClass('export');};e.preventDefault();soc.ajax('Shared','Export','run',data,function(response){if(response.result){notifyUI();}});}).one('click','a[data-sync="1"]',function(e){var link=$(this),icon=$('.fa',link);icon.removeClass('fa-cloud-upload').addClass('fa-spinner fa-spin');link.text(' Syncing...').prepend(icon);soc.ajax('Shared','Sync','run',link.data());e.preventDefault();});}}};module.admin={config:{api:{higher_logic:{soap:{init:function(){$('.s-ad-cfg-api-higher-logic-soap').on('click','.soap-show-token',function(e){e.preventDefault();soc.ajax('HigherLogic','Soap_A_SoapApi','showApiToken');}).on('click','.soap-init-token',function(e){e.preventDefault();soc.ajax('HigherLogic','Soap_A_SoapApi','resetApiToken');}).on('click','.soap-reset-token',function(e){e.preventDefault();var resolution=$.Deferred();resolution.done(function(){soc.ajax('HigherLogic','Soap_A_SoapApi','resetApiToken');});soc.confirm('Are you sure you want to reset the authentication token?',resolution,{});});}}}}},sidebar:{s_class:'.s-ad-sidebar-editor',site:null,editor:function(site){module.admin.sidebar.site=site;$(module.admin.sidebar.s_class).on('click','[data-action]',function(e){var action=$(e.currentTarget).data('action')+"Action";if(typeof module.admin.sidebar[action]==="function"){module.admin.sidebar[action]();}}).on('click',module.admin.sidebar.widget.w_class+' button[data-action]',function(e){var triggerer=$(e.currentTarget),action=triggerer.data('action'),widget=triggerer.closest(module.admin.sidebar.widget.w_class);if(typeof module.admin.sidebar.widget[action]==="function"){module.admin.sidebar.widget[action].call(widget);}})},ajax:function(method,data){data.site=module.admin.sidebar.site;soc.ajax('Gui','Sidebar_A_Editor',method,data);},widget:{status:{DELETED:'deleted',ADDED:'added',UPDATED:'updated'},w_class:'.s-ad-sidebar-widget',label_class:'.s-ad-sidebar-label',up:function(){var order=parseInt(this.data('order'),10);if(order===0){return;}
this.siblings(module.admin.sidebar.widget.w_class+'[data-order="'+(order-1)+'"]').before(this);module.admin.sidebar.resetOrders();module.admin.sidebar.showChanges();},remove:function(){var d=$.Deferred(),that=this;d.done(function(){that.addClass('list-group-item-danger').data('status',module.admin.sidebar.widget.status.DELETED).addClass('s-ad-sidebar-widget-status-deleted');$(module.admin.sidebar.widget.label_class,that).toggleClass('label-danger label-default').removeClass('hide').text('Deleted');$('button',that).attr('disabled','disabled');module.admin.sidebar.showChanges();});soc.confirm('Are you sure you want to delete this widget?',d,{});},edit:function(){module.admin.sidebar.ajax('edit',{"widget":this.data()});},update:function(config){this.addClass('list-group-item-warning s-ad-sidebar-widget-status-updated').data('status',module.admin.sidebar.widget.status.UPDATED);$(module.admin.sidebar.widget.label_class,this).removeClass('hide label-default').addClass('label-warning').text('Updated');this.data('config',config);}},resetOrders:function(){$(module.admin.sidebar.widget.w_class+':visible').each(function(index,item){$(item).data('order',(index+1)).attr('data-order',(index+1));});},showChanges:function(){module.admin.sidebar.toggleChanges(true);soc.setUnloadWarning('You have unsaved changes.');},hideChanges:function(){module.admin.sidebar.toggleChanges(false);soc.clearUnloadWarning();},toggleChanges:function(status){var editor=$(module.admin.sidebar.s_class);if(editor.data('changed')===status){return;}
$('.s-ad-sidebar-editor-tools-toggle').toggleClass('hide');$('.panel-body .panel',editor).toggleClass('panel-default panel-warning');editor.data('changed',status);},addWidget:function(object){module.admin.sidebar.showChanges();var clone=$('.s-ad-sidebar-widget[data-clone]').clone();clone.removeData().attr('data-widget',object.widget).attr('data-order',($(module.admin.sidebar.widget.w_class+':visible').length+1)).data('status',module.admin.sidebar.widget.status.ADDED).attr('data-id',object.id).removeClass('hide').removeAttr('data-clone').find('.s-ad-sidebar-editor-widget-title').text(object.title);clone.insertAfter($(module.admin.sidebar.widget.w_class+':visible:last'));},postEdit:function(response){module.admin.sidebar.showChanges();var widget=$(module.admin.sidebar.widget.w_class+'[data-id="'+response.widget.id+'"]');module.admin.sidebar.widget.update.call(widget,response.config);},saveSuccess:function(){module.admin.sidebar.hideChanges();$('.s-ad-sidebar-widget-status-deleted').remove();$('.s-ad-sidebar-widget-status-updated').removeClass('list-group-item-warning').find(module.admin.sidebar.widget.label_class).addClass('hide');},resetAction:function(){var d=$.Deferred().done(function(){soc.clearUnloadWarning();window.location.reload();});soc.confirm('Are you sure you want to reset all changes?',d,{})},saveAction:function(){module.admin.sidebar.ajax('save',{sidebar:module.admin.sidebar.getSidebar()});},previewAction:function(){module.admin.sidebar.ajax('preview',{sidebar:module.admin.sidebar.getSidebar()});},getSidebar:function(){var sidebar=[];$(module.admin.sidebar.widget.w_class+':visible').each(function(i,widget){var data=$(widget).data();if(!data.status||data.status!==module.admin.sidebar.widget.status.DELETED){sidebar.push(data);}});return sidebar;}}};module.search={demo:{stylesheetPath:'http://cdn.shooju.com/ms/v1/shooju-managed-search.css',jsPath:'http://cdn.shooju.com/ms/v1/shooju-managed-search.js',settingsPath:'js/soc/search-demo.js',init:function(){$('<link>').attr({'rel':'stylesheet','href':module.search.demo.stylesheetPath}).appendTo('head');soc.loader.load(module.search.demo.jsPath);soc.loader.whenLoaded(module.search.demo.jsPath,function(){new ShoojuManagedSearch('.shooju-msearch',module.search.demo.settingsPath);});}}};module.product={reqadd:{add_products:function(products){soc.module.product.reqadd._queue=products;soc.module.product.reqadd.add_product_to_cart();},add_product_to_cart:function(){var product=soc.module.product.reqadd._queue.pop();if(!product){soc.redirectReplace('p/pr/qu');return;}
var params={prodid:product.id,quantity:product.qty,modal:'soc.module.product.reqadd.add_product_to_cart'};soc.ajax('pr','qu','edit',params,soc.module.product.reqadd.add_product_callback);},add_product_callback:function(data){if(!data){return;}
soc.ajOp(data);var hasLightbox=false;$.each(data,function(idx,datai){if(datai.op&&datai.op=="lb"){hasLightbox=true;}});if(!hasLightbox){soc.module.product.reqadd.add_product_to_cart();}}}};module.survey={notifications:{init:function(){$('.s-su-notification-response').on('change','.inline-response',function(e){var params={'response_inline':e.target.checked?1:0,'sid':$(e.target).data('survey_id'),'type':$(e.target).data('notify_type')};soc.ajax('Survey','Notifications','includeResponseInline',params);});}}}})(jQuery,soc.module);(function($,plugins){plugins.registry=[];plugins.init=function(){plugins.video.boot();$.each(plugins.registry,function(i,plug){plug();});};plugins.video={path:'js/vendor/mediaelement/',scriptFile:'mediaelement-and-player.min.js',cssFile:'mediaelementplayer.css',boot:function(){if($('video,audio').length>0){plugins.registry.push(function(){plugins.video.init.call(plugins.video);});}},init:function(options){if(!soc.loader.isLoaded(this.path+this.scriptFile)){this.addCss();this.loadSrc();}
if(!options||!options.init||options.init.autoload){this.fixSources();this.loadMedia((options&&options.player?options.player:{}));}},loadSrc:function(){soc.loader.load(this.path+this.scriptFile);},loadMedia:function(config){var params=$.extend({},{pluginPath:this.path,success:$.proxy(this.postLoad,this)},config||{});soc.loader.whenLoaded(this.path+this.scriptFile,function(){$('video,audio').mediaelementplayer(params);});},postLoad:function(){$('video').each(function(){if($('source[type="video/vimeo"]',this).length===1){$(this).closest('.mejs-container').find('.mejs-controls').hide();}else if($('source[type="video/youtube"]',this).length===1){$(this).closest('.mejs-container').find('.mejs-overlay-button').hide();}});},addCss:function(){$('head').append('<link rel="stylesheet" href="'+this.path+this.cssFile+'" />');},fixSources:function(){$('video > source').each(function(){var t=$(this);if(/youtube\.com/.test(t.attr('src'))){t.attr('type','video/youtube');t.attr('src',function(i,v){return v.replace('embed/','watch?v=')});}else if(/vimeo\.com/.test(t.attr('src'))){t.attr('type','video/vimeo');}});}}})(jQuery,soc.plugins||{});